"""empty message

Revision ID: 5521a93caa1a
Revises: 35b22e87f5f4
Create Date: 2019-08-22 19:02:07.805511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5521a93caa1a'
down_revision = '35b22e87f5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    op.add_column('user', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'product_id')
    op.add_column('products', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('products_ibfk_1', 'products', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
