"""empty message

Revision ID: 9f281c145d77
Revises: 5521a93caa1a
Create Date: 2019-08-22 19:32:31.572609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f281c145d77'
down_revision = '5521a93caa1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=130), nullable=True))
    op.create_unique_constraint(None, 'products', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
