"""empty message

Revision ID: bbf91365387c
Revises: d67acac1bb30
Create Date: 2019-08-21 15:18:05.071239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbf91365387c'
down_revision = 'd67acac1bb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'country',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'state',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'zipcode',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'zipcode',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'state',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'country',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
